version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn 
  build:
    commands:
      - echo Build started on `date`
      - make build-patanttime
artifacts:
  discard-paths: yes
  type: zip
  files:
    - functions/patanttime/deploy/patanttimeSamTemplate.yaml
